name: Run tests to compare C and Python outputs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests to compare C and Python outputs
        run: |
          sudo apt install -y build-essential python-is-python3
          make
          python3 test_c_and_python_outputs.py
